# Generated by Django 5.1.4 on 2025-01-14 10:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=255)),
                ('owners_name', models.CharField(max_length=100)),
                ('flock_size', models.IntegerField()),
                ('tag', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClimateControlData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heater', models.BooleanField(default=False)),
                ('cooling_fan', models.BooleanField(default=False)),
                ('humidifier', models.BooleanField(default=False)),
                ('exhaust_fan', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='climate_control_data', to='devicedata.devicedata')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField()),
                ('humidity', models.FloatField()),
                ('gas_sensor', models.FloatField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sensor_data', to='devicedata.devicedata')),
            ],
        ),
        migrations.CreateModel(
            name='ThresholdData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('highest_temperature_level', models.FloatField()),
                ('lowest_temperature_level', models.FloatField()),
                ('highest_humidity_level', models.FloatField()),
                ('lowest_humidity_level', models.FloatField()),
                ('highest_ammonia_level', models.FloatField()),
                ('lowest_ammonia_level', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='threshold_data', to='devicedata.devicedata')),
            ],
        ),
    ]
